# Generated by Django 4.0.6 on 2022-07-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
